version: "3.3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ${MYSQL_CONFIG_FILE}:/etc/my.cnf
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_SCRIPTS_DIR}:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: 'mygramdb'
      MYSQL_ROOT_PASSWORD: 'user'
    ports:
      - 3306:3306
